export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST';
export const ANSWER_REQUEST = 'ANSWER_REQUEST';

export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';

export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';
export const ANSWER_ERROR = 'ANSWER_ERROR';
export const RAISE_ERROR = 'RAISE_ERROR';

export const FILTER_CHANGE = 'FILTER_CHANGE';
export const SET_AUTH = 'SET_AUTH';
export const SILENT_AUTH_REQUEST = 'SILENT_AUTH_REQUEST';